### ISSUE TITLE
Общее: Поля и кнопки стали слишком маленькие по высоте

### ISSUE THREAD

**Issue by 7ellys** [DivanDesign/EvolutionCMS.plugins.ManagerManager.mm_ddMultipleFields#14]
![photo5197319575790791473](https://user-images.githubusercontent.com/39525589/40367480-f5b28cf4-5df2-11e8-8b3e-6f38c25d2fbf.jpg)

Текст не входит в поле/кнопку, наполовину обрезается.

**Comment by Ronef** [comment]
913043e9d14d3888367688d83efff537113eeb92
